In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
df=pd.read_csv("car_fuel_efficiency_2026.csv")

In [6]:
df.sample(5) #to get an ovrview of data

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
8570,1991,USA,Diesel,Rear-wheel drive,4,2270,6,253.0,4220,20.4,29.2
5060,1994,USA,Gasoline,Front-wheel drive,3,2180,6,252.0,4230,19.9,26.2
8148,1994,Europe,Gasoline,Front-wheel drive,2,1960,6,212.0,3880,17.9,29.1
3214,1994,Asia,Gasoline,Front-wheel drive,3,2180,6,235.0,4130,17.5,30.1
2757,1978,Europe,Gasoline,Front-wheel drive,3,1870,5,220.0,3600,17.3,29.3

In [8]:
df.shape #to get rows and columns Q2

(10000, 11)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [11]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [15]:
df['vehicle_weight']

0       3870
1       4210
2       4240
3       4490
4       4510
        ...
9995    4690
9996    4370
9997    4590
9998    4450
9999    4370
Name: vehicle_weight, Length: 10000, dtype: int64

In [16]:
df['fuel_type'].nunique()

3

In [17]:
original_median = df["horsepower"].median()

print(original_median)

254.0

In [20]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].median())

In [22]:
new_median = df["horsepower"].median()

print(new_median) #therefore old median is same as new

254.0

In [ ]:
#have a doubt in last qn about how we are supposed to solve it